language: "node"
node_js: 12
cache: yarn
before_install: cd front # this affects the entire job, including deploy
install: yarn
script: yarn build # this is just to check that build will not fail before running semantic-release
before_deploy:
  - yarn semantic-release
  - yarn build
deploy:
  provider: S3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "pento.danielo.es"
  region: $AWS_DEFAULT_REGION
  local_dir: ./build
  on:
    branch: master
